version: "3.8"

services:
  accreditations:
    build:
      context: . 
      dockerfile: accreditations/Dockerfile
    container_name: accreditations-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/selling_points_db
    networks:
      - challenge-network
    depends_on:
      - redis
      - mongodb

  selling-points:
    build:
      context: .
      dockerfile: selling-points/Dockerfile
    container_name: selling-points-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/selling_points_db
    networks:
      - challenge-network
    depends_on:
      - redis
      - mongodb

  selling-costs:
    build:
      context: .
      dockerfile: selling-costs/Dockerfile
    container_name: selling-costs-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/selling_points_db
    networks:
      - challenge-network
    depends_on:
      - redis
      - mongodb

  commons:
    build:
      context: .
      dockerfile: commons/Dockerfile 
    container_name: commons-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/selling_points_db
    networks:
      - challenge-network
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - challenge-network
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=selling_points_db
    networks:
      - challenge-network
    volumes:
      - mongodb_data:/data

networks:
  challenge-network:

volumes:
  redis_data:
  mongodb_data:
